name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels: [ 'feature', 'enhancement' ]
  - title: '🐛 Fixes'
    labels: [ 'bug', 'fix' ]
  - title: '🧰 Maintenance'
    labels: [ 'chore', 'ci', 'docs', 'refactor' ]

template: |
  ## What’s new
  $CHANGES

  ## Thanks
  Thanks to everyone who contributed!
