services:
  ollama:
    image: ollama/ollama:latest
    container_name: uaeng-ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=5m
    volumes:
      - ollama:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    command: ["serve"]
volumes:
  ollama: {}
