name: clang-tidy

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy ninja-build cmake build-essential

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy on src/*.c
        run: |
          jq -r '.[] | select(.file | endswith(".c")) | .file' build/compile_commands.json | sort -u | xargs -n1 -I{} bash -c 'echo "::group::clang-tidy {}"; clang-tidy {} -- -Iinclude -Isrc; echo "::endgroup::"'
