name: clang-format check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Check formatting
        run: |
          git ls-files '*.c' '*.h' | xargs -r clang-format -style=file -Werror -n
