name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    name: Build & Upload Release Artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact: uaengine-linux-x64.tar.gz
          - os: macos-latest
            artifact: uaengine-macos-x64.tar.gz
          - os: windows-latest
            artifact: uaengine-windows-x64.zip

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          tar -C build -czf ${{
            (runner.os == 'Linux' && 'uaengine-linux-x64.tar.gz') ||
            (runner.os == 'macOS' && 'uaengine-macos-x64.tar.gz')
          }} uaengine

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell -Command "Compress-Archive -Path .\build\uaengine.exe -DestinationPath uaengine-windows-x64.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  publish:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
